### ISSUE TITLE
feat: make scrollbars the same visually across platforms

### ISSUE THREAD

**Issue by knowler** [impress-org/givewp-campaigns#137]
# Feature Request

## User Story

As a product designer, I want my product to visually look similar or the same across various platforms.

As a user, I want a clean, understandable user interface so I can use the app.

As a developer, I do not want cross browser issues ’cause those are a headache.

## Possible Solution

I am going to try out [SimpleBar](https://github.com/Grsmto/simplebar) for this since its apparently lightweight and seems to be well supported (and Storybook uses it, so it can be trusted).

## Acceptance Criteria

- [ ] Scroll bars should visually looks the same across platforms (macOS, Windows, Linux) and different browsers (Chrome, Firefox, Safari, Edge, mobile browsers).
- [ ] Scroll bars should ideally respect the user’s system preference about scroll bars.

**Comment by DevinWalker** [comment]
SimpleBar looks fancy! I like it.

**Comment by DevinWalker** [comment]
A few arguments against using SimpleBar:

1. With a few CSS tweaks the scrollbars look nice on my system now (see #165)
2. Implementing SimpleBar is seemingly more complex than a turnkey solution 
3. Users on Windows and Linux are used to seeing the OS' native scrollbars; However ugly we feel they may be as MacOS users they likely don't mind it (otherwise they would be more motivated to move over to Mac).
4. Despite how lightweight SimpleBar is, it still ads more weight than native scrollbars.

**Comment by mikejhale** [comment]
For reference, this is what the scroll bars look like on Windows 10, Chrome 78:

https://www.loom.com/share/3b4f46b7a69c43b7b843d9e000d85ba5

When the window is large enough, Windows/Chrome has disabled scrollbars at the right of the settings sidebar, at the bottom of the preview pane, and at the right of the preview pane. The scroll bars, when they do appear, are not unlike other apps, but most apps do not show a disabled scrollbar where one is not needed and that uses screen space unnecessarily and looks unpolished.

**Comment by DevinWalker** [comment]
Closing this - native scrollbars appear working nicely across browsers now since the protoype.
